### ISSUE TITLE
NO Dgs7000_sdfestim02_sdfnorm02_level03_decim1000000.ply NOR ./output/refined_ply// DIRECTORY CREATED

### ISSUE THREAD

**Issue by nbmontasufv** [Anttwo/SuGaR#113]
Hi, thanks for sharing your work with everybody:

I have the same issue over here (on Windows machine):
=> No .ply, no ./output/refined_ply// directory created either.

Error message:
RPly: Unable to open file
[Open3D WARNING] Read PLY failed: unable to open file: ./output/coarse_mesh\gaussian_splatting\data\templos\01\sugarmesh_coarse\gaussian_splatting\data\templos\01\3Dgs7000_sdfestim02_sdfnorm02_level03_decim1000000.ply
Mesh to bind to loaded.
Binding radiance cloud to surface mesh...
Traceback (most recent call last):
File "D:\sugar_local_clone\SuGaR\train.py", line 170, in
refined_sugar_path = refined_training(refined_args)
File "D:\sugar_local_clone\SuGaR\sugar_trainers\refine.py", line 396, in refined_training
sugar = SuGaR(
File "D:\sugar_local_clone\SuGaR\sugar_scene\sugar_model.py", line 323, in init
scales = scales.clamp_min(0.0000001).reshape(len(faces_verts), -1, 1).expand(-1, self.n_gaussians_per_surface_triangle, 2).clone().reshape(-1, 2)
RuntimeError: cannot reshape tensor of 0 elements into shape [0, -1, 1] because the unspecified dimension size -1 can be any value and is ambiguous

Thank you for any heads up concerning this issue.

Best,

Nelson

**Comment by Anttwo** [comment]
Hello @nbmontasufv,

Thank you for your nice words!

Are you using Windows?
Unfortunately, the code currently encounters some issues with Windows. 
The problem is a convention for writing paths: Windows uses `\` as a separator in paths but Linux and MacOS use `/`. 
I plan to fix this very soon, I'm really sorry for this.

_(In the meantime, if you like to run research code from GitHub --often written for Linux-- on your computer, you can take a look at [WSL2 (Windows Subsystem for Linux v2](https://learn.microsoft.com/en-us/windows/wsl/install)). WSL2 is a free and great tool from Microsoft that lets you use a Linux console in your Windows OS. I use WSL2 on my personal Windows machine, and it really makes life simpler for running research code built for Linux and for developers experimenting with computer science stuff in general)_

Best,
Antoine

**Comment by nbmontasufv** [comment]
Hi,
Thank you for your quick response and great work. Your modeling and code writing is phenomenal.

Yes, I'm trying to run it on windows. I saw a similar problem in another issue and I'm trying to fix it right now: I tried to change the .split("/") and "./output/coarse"; "/ouput/meshes" etc. but have not been successful to bypass it. I'll get back to you if I find a solution.

Again, thanks so much for your wonderful work and getting back to me.

**Comment by citystrawman** [comment]
> Hi, Thank you for your quick response and great work. Your modeling and code writing is phenomenal.
> 
> Yes, I'm trying to run it on windows. I saw a similar problem in another issue and I'm trying to fix it right now: I tried to change the .split("/") and "./output/coarse"; "/ouput/meshes" etc. but have not been successful to bypass it. I'll get back to you if I find a solution.
> 
> Again, thanks so much for your wonderful work and getting back to me.

HI, I just encountered a similar issue, I've updated the os separator, but from the code I could only see that `sugar_mesh_path` is created, but the corresponding .ply is not, and then the code starts loading the mesh by `o3d.io.read_triangle_mesh(sugar_mesh_path)`, which is impossible. So may I know  how did you solved this issue?

**Comment by nbmontasufv** [comment]
> > Hi, Thank you for your quick response and great work. Your modeling and code writing is phenomenal.
> > Yes, I'm trying to run it on windows. I saw a similar problem in another issue and I'm trying to fix it right now: I tried to change the .split("/") and "./output/coarse"; "/ouput/meshes" etc. but have not been successful to bypass it. I'll get back to you if I find a solution.
> > Again, thanks so much for your wonderful work and getting back to me.
> 
> HI, I just encountered a similar issue, I've updated the os separator, but from the code I could only see that `sugar_mesh_path` is created, but the corresponding .ply is not, and then the code starts loading the mesh by `o3d.io.read_triangle_mesh(sugar_mesh_path)`, which is impossible. So may I know how did you solved this issue?

Hi,

I'm kind of halfway through it. For now I managed to get the "coarse_mesh.py" script to create the :PLY file 
![PLY_file_created](https://github.com/Anttwo/SuGaR/assets/153820350/91b49bc0-1a31-4f5f-8eae-293b0ff8a6a7)

For it to create the .PLY file, in "coarse_mesh.py" I changed the following:

LINES 67-72: Change  **args.scene_path.split("/")** FOR **args.scene_path.split(os.sep)**
# Mesh output dir
    if args.mesh_output_dir is None:
        if len(args.scene_path.split(os.sep)[-1]) > 0: # if len(args.scene_path.split("/")[-1]) > 0:
            args.mesh_output_dir = os.path.join("./output/coarse_mesh", args.scene_path.split(os.sep)[-1]) #args.scene_path.split("/")[-1])
        else:
            args.mesh_output_dir = os.path.join("./output/coarse_mesh", args.scene_path.split(os.sep)[-2]) #args.scene_path.split("/")[-1]) 

LINE 477: Change  **sugarmesh_' + sugar_checkpoint_path.split('/')** FOR **sugarmesh_' + sugar_checkpoint_path.split(os.sep)**
else:
      sugar_mesh_path = 'sugarmesh_' + sugar_checkpoint_path.split(os.sep)[-2].replace('sugarcoarse_', '') + '_levelZZ_decimAA.ply' #sugar_checkpoint_path.split('/')[-2].

LINE 610: Change  **sugarmesh_' + sugar_checkpoint_path.split('/')** FOR **sugarmesh_' + sugar_checkpoint_path.split(os.sep)**
else:
  sugar_mesh_path = 'sugarmesh_' + sugar_checkpoint_path.split(os.sep)[-2].replace('sugarcoarse_', '') + '_poissoncenters_decimAA.ply' #sugar_checkpoint_path.split('/')

LINE 743: Change  **sugar_checkpoint_path.split('/')** FOR **sugar_checkpoint_path.split(os.sep)**
else:
  sugar_mesh_path = 'sugarmesh_' + sugar_checkpoint_path.split(os.sep)[-2].replace('sugarcoarse_', '') + 'marchingcubes_levelZZ_decimAA.ply'  

But the "refined_mesh.py" halts when trying to open it cause it duplicates the path when trying to access it and can't find it (my guess is that I have to do the same "os.sep" changes for it to work but i haven't tried it yet). I'll try to sort this later, don't have the time right now, please  let me know if you manage to fix it.

Best, 

Nelson

**Comment by citystrawman** [comment]
> > > Hi, Thank you for your quick response and great work. Your modeling and code writing is phenomenal.
> > > Yes, I'm trying to run it on windows. I saw a similar problem in another issue and I'm trying to fix it right now: I tried to change the .split("/") and "./output/coarse"; "/ouput/meshes" etc. but have not been successful to bypass it. I'll get back to you if I find a solution.
> > > Again, thanks so much for your wonderful work and getting back to me.
> > 
> > 
> > HI, I just encountered a similar issue, I've updated the os separator, but from the code I could only see that `sugar_mesh_path` is created, but the corresponding .ply is not, and then the code starts loading the mesh by `o3d.io.read_triangle_mesh(sugar_mesh_path)`, which is impossible. So may I know how did you solved this issue?
> 
> Hi,
> 
> I'm kind of halfway through it. For now I managed to get the "coarse_mesh.py" script to create the :PLY file ![image](https://private-user-images.githubusercontent.com/153820350/300859680-0e804318-6653-4ceb-b375-6ef1d8259ca7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY2MzIyODUsIm5iZiI6MTcwNjYzMTk4NSwicGF0aCI6Ii8xNTM4MjAzNTAvMzAwODU5NjgwLTBlODA0MzE4LTY2NTMtNGNlYi1iMzc1LTZlZjFkODI1OWNhNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEzMFQxNjI2MjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yM2U0YTBjYzYzZGJiMmYyZTljOTcwNTgxMWMyODE1MGM0ZjE2MWM0Y2VmZDg4YjNiMGM1MTk4YjE1NDg0MmVlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.cPye7UFGyHW7gfnVvYBCgk_Pb24herN5MIlUzJK750U)
> 
> For it to create the .PLY file, in "coarse_mesh.py" I changed the following:
> 
> LINES 67-72: Change **args.scene_path.split("/")** FOR **args.scene_path.split(os.sep)**
> 
> # Mesh output dir
> ```
> if args.mesh_output_dir is None:
>      if len(args.scene_path.split(os.sep)[-1]) > 0: # if len(args.scene_path.split("/")[-1]) > 0:
>          args.mesh_output_dir = os.path.join("./output/coarse_mesh", args.scene_path.split(os.sep)[-1]) #args.scene_path.split("/")[-1])
>      else:
>          args.mesh_output_dir = os.path.join("./output/coarse_mesh", args.scene_path.split(os.sep)[-2]) #args.scene_path.split("/")[-1]) 
> ```
> 
> LINE 477: Change **sugarmesh_' + sugar_checkpoint_path.split('/')** FOR **sugarmesh_' + sugar_checkpoint_path.split(os.sep)**
> 
> ```
> else:
>       sugar_mesh_path = 'sugarmesh_' + sugar_checkpoint_path.split(os.sep)[-2].replace('sugarcoarse_', '') + '_levelZZ_decimAA.ply' #sugar_checkpoint_path.split('/')[-2].
> ```
> 
> LINE 610: Change **sugarmesh_' + sugar_checkpoint_path.split('/')** FOR **sugarmesh_' + sugar_checkpoint_path.split(os.sep)**
> 
> ```
> else:
>   sugar_mesh_path = 'sugarmesh_' + sugar_checkpoint_path.split(os.sep)[-2].replace('sugarcoarse_', '') + '_poissoncenters_decimAA.ply' #sugar_checkpoint_path.split('/')
> ```
> 
> LINE 743: Change **sugar_checkpoint_path.split('/')** FOR **sugar_checkpoint_path.split(os.sep)**
> 
> ```
> else:
>   sugar_mesh_path = 'sugarmesh_' + sugar_checkpoint_path.split(os.sep)[-2].replace('sugarcoarse_', '') + 'marchingcubes_levelZZ_decimAA.ply'  
> ```
> 
> However, the "refined_mesh.py" halts when trying to open it cause it duplicates the path when trying to access it and can't find it (I don't know why it does it, but my guess is that I have to do the same "os.sep" changes for it to work but I haven't tried it yet). I'll try to sort this later, don't have the time right now, please let me know if you manage to fix it.
> 
> Best,
> 
> Nelson

Hi, please refer to this post: https://github.com/Anttwo/SuGaR/issues/66  and I followed OuOu2021 and Kitmallet 's advices and then there's no issue about the directory inconsistency. but I still got one issue that ` sugar_mesh_path` in `refined_mesh.py` is not correctly defined: `sugar_mesh_path` is the location of a .ply file that is saved in another place in previous stage. Thus I changed  `sugar_mesh_path` as follows:
![image](https://github.com/Anttwo/SuGaR/assets/9004748/39a9bb53-7b50-422b-8ae4-1443bf0c03b8)
then I can run the whole program and get an obj mesh.  
Hope you can make it :)

**Comment by pyjacques** [comment]
Hello, First thanks @Anttwo for this amazing work !
Making these adjustments to 'coarse_mesh.py' and 'refined_mesh.py', i've create my first refined Gaussians. 🤩
output files:
![image](https://github.com/Anttwo/SuGaR/assets/44160710/03d01c1c-25e6-4025-8287-1c55abfab4c4)
--> Refined .ply is OK, but no .obj ?!
Command used:
```powershell
cd conda\SuGaR
conda activate sugar
python train.py -s gaussian_splatting\input_data\HC-2-VC\ -c gaussian_splatting\input_data\HC-2-VC\output\ -r "density"
``` 
I've got an error at "Binding radiance cloud to surface mesh..." step :
```powershell
...
Training finished after 15000 iterations with loss=0.022915204986929893.
Saving final model...
Final model saved.

Exporting ply file with refined Gaussians...
Ply file exported. This file is needed for using the dedicated viewer.
==================================================
Starting extracting texture from refined SuGaR model:
Scene path: gaussian_splatting\input_data\h-pass-c-3e\
Iteration to load: 7000
Vanilla 3DGS checkpoint path: gaussian_splatting\input_data\h-pass-c-3e\output\
Refined model path:
./output/refined\gaussian_splatting\input_data\h-pass-c-3e\sugarfine_coarse_mesh\h-pass-c-3e\h-pass-c-3e_level03_decim10
00000_normalconsistency01_gaussperface1/15000.pt
Coarse mesh path:
gaussian_splatting\input_data\h-pass-c-3e\gaussian_splatting\input_data\h-pass-c-3e\refined\gaussian_splatting\input_dat
a\h-pass-c-3e\sugarmesh_coarse_mesh\h-pass-c-3e\h-pass-c-3e_level03_decim1000000_normalconsistency01.ply
Mesh output directory: .\output\refined_mesh\gaussian_splatting\input_data\h-pass-c-3e\
Mesh save path:
.\output\refined_mesh\gaussian_splatting\input_data\h-pass-c-3e\refined\gaussian_splatting\input_data\h-pass-c-3e\sugarf
ine_coarse_mesh\h-pass-c-3e\h-pass-c-3e_level03_decim1000000_normalconsistency01_gaussperface1.obj
Number of gaussians per surface triangle: 1
Square size: 10
Postprocess mesh: False
==================================================
Source path: gaussian_splatting\input_data\h-pass-c-3e\
Gaussian splatting checkpoint path: gaussian_splatting\input_data\h-pass-c-3e\output\

Loading Vanilla 3DGS model config gaussian_splatting\input_data\h-pass-c-3e\output\...
Found image extension .png
Vanilla 3DGS Loaded.
65 training images detected.
The model has been trained for 7000 steps.
0.534775 M gaussians detected.
RPly: Unable to open file
[Open3D WARNING] Read PLY failed: unable to open file: gaussian_splatting\input_data\h-pass-c-3e\gaussian_splatting\input_data\h-pass-c-3e\refined\gaussian_splatting\input_data\h-pass-c-3e\sugarmesh_coarse_mesh\h-pass-c-3e\h-pass-c-3e_level03_decim1000000_normalconsistency01.ply
Binding radiance cloud to surface mesh...
Traceback (most recent call last):
  File "E:\conda\SuGaR\train.py", line 189, in <module>
    refined_mesh_path = extract_mesh_and_texture_from_refined_sugar(refined_mesh_args)
  File "E:\conda\SuGaR\sugar_extractors\refined_mesh.py", line 112, in extract_mesh_and_texture_from_refined_sugar
    refined_sugar = SuGaR(
  File "E:\conda\SuGaR\sugar_scene\sugar_model.py", line 323, in __init__
    scales = scales.clamp_min(0.0000001).reshape(len(faces_verts), -1, 1).expand(-1, self.n_gaussians_per_surface_triangle, 2).clone().reshape(-1, 2)
RuntimeError: cannot reshape tensor of 0 elements into shape [0, -1, 1] because the unspecified dimension size -1 can be any value and is ambiguous

(sugar) E:\conda\SuGaR>
``` 

I've tried also to setup conda env under ubuntu22 in WSL2/Win11 without success yet (cuda ok but not tensorflow)... 
I've found to guide :
https://gist.github.com/neouranos/51dd12d9471eb73b2348d373b605b45a
https://gist.github.com/Ayke/5f37ebdb84c758f57d7a3c8b847648bb
Trying again... Hope you will have time to fix code for Windows soon 🤞

**Comment by zhenguapi** [comment]
> ```
> (sugar) pyjacques@PC-PY-FIXE:~/SuGaR$ cd gaussian_splatting/submodules/diff-gaussian-rasterization/
> pip install -e .
> cd ../simple-knn/
> pip install -e .
> cd ../../../
> Defaulting to user installation because normal site-packages is not writeable
> Obtaining file:///home/pyjacques/SuGaR/gaussian_splatting/submodules/diff-gaussian-rasterization
>   Preparing metadata (setup.py) ... done
> Installing collected packages: diff-gaussian-rasterization
>   Running setup.py develop for diff-gaussian-rasterization
> Successfully installed diff-gaussian-rasterization-0.0.0
> Defaulting to user installation because normal site-packages is not writeable
> Obtaining file:///home/pyjacques/SuGaR/gaussian_splatting/submodules/simple-knn
>   Preparing metadata (setup.py) ... done
> Installing collected packages: simple-knn
>   Running setup.py develop for simple-knn
> Successfully installed simple-knn-0.0.0
> (sugar) pyjacques@PC-PY-FIXE:~/SuGaR$ python train.py -s gaussian_splatting\input_data\h-pass-c-3e\ -c gaussian_splatting\input_data\h-pass-c-3e\output\ -r "density"
> Traceback (most recent call last):
>   File "/home/pyjacques/SuGaR/train.py", line 3, in <module>
>     from sugar_trainers.coarse_density import coarse_training_with_density_regularization
>   File "/home/pyjacques/SuGaR/sugar_trainers/coarse_density.py", line 7, in <module>
>     from sugar_scene.gs_model import GaussianSplattingWrapper, fetchPly
>   File "/home/pyjacques/SuGaR/sugar_scene/gs_model.py", line 6, in <module>
>     from gaussian_splatting.scene.gaussian_model import GaussianModel
>   File "/home/pyjacques/SuGaR/gaussian_splatting/scene/__init__.py", line 16, in <module>
>     from scene.dataset_readers import sceneLoadTypeCallbacks
>   File "/home/pyjacques/SuGaR/./gaussian_splatting/scene/__init__.py", line 16, in <module>
>     from scene.dataset_readers import sceneLoadTypeCallbacks
>   File "/home/pyjacques/SuGaR/./gaussian_splatting/scene/dataset_readers.py", line 24, in <module>
>     from scene.gaussian_model import BasicPointCloud
>   File "/home/pyjacques/SuGaR/./gaussian_splatting/scene/gaussian_model.py", line 20, in <module>
>     from simple_knn._C import distCUDA2
> ModuleNotFoundError: No module named 'simple_knn'
> (sugar) pyjacques@PC-PY-FIXE:~/SuGaR$
> ```
> 
> I have "Successfully installed simple-knn-0.0.0" but "ModuleNotFoundError: No module named 'simple_knn'"
> 
> Trying again... Any advice?

  Hello@[pyjacques](https://github.com/pyjacques), about "ModuleNotFoundError: No module named 'simple_knn'" , perhaps you can refer to this: https://github.com/graphdeco-inria/gaussian-splatting/issues/880#issuecomment-2241621568

**Comment by NelsonBML** [comment]
Hi @Anttwo,

I have modified your original SuGaR implementation so it works on Windows. Also, I noticed that you recently updated the repo with new files and some changes. If you like, I can share it with you on a separate repo or send it your way via another channel of your choice so you can adapt it to your updated implementation. 

Happy Holidays and thanks again for your work.

Best regards,

Nelson
