### ISSUE TITLE
Collecting package metadata (current_repodata.json): failed

### ISSUE THREAD

**Issue by tapowanliwuyun** [Anttwo/SuGaR#124]
Hello, your job is great! I encountered some issues during the installation process of the environment. I am running commands

`conda install -c fvcore -c iopath -c conda-forge fvcore iopath`

When encountering an error

```
Collecting package metadata (current_repodata.json): failed

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/home/amax/anaconda3/lib/python3.10/site-packages/conda/gateways/repodata/__init__.py", line 161, in conda_http_errors
        yield
      File "/home/amax/anaconda3/lib/python3.10/site-packages/conda/gateways/repodata/__init__.py", line 127, in repodata
        response.raise_for_status()
      File "/home/amax/anaconda3/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
        raise HTTPError(http_error_msg, response=self)
    requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://conda.anaconda.org/fvcore/linux-64/current_repodata.json
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/amax/anaconda3/lib/python3.10/site-packages/requests/models.py", line 971, in json
        return complexjson.loads(self.text, **kwargs)
      File "/home/amax/anaconda3/lib/python3.10/site-packages/simplejson/__init__.py", line 514, in loads
        return _default_decoder.decode(s)
      File "/home/amax/anaconda3/lib/python3.10/site-packages/simplejson/decoder.py", line 386, in decode
        obj, end = self.raw_decode(s)
      File "/home/amax/anaconda3/lib/python3.10/site-packages/simplejson/decoder.py", line 416, in raw_decode
        return self.scan_once(s, idx=_w(s, idx).end())
    simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/amax/anaconda3/lib/python3.10/site-packages/conda/exceptions.py", line 1132, in __call__
        return func(*args, **kwargs)
      File "/home/amax/anaconda3/lib/python3.10/site-packages/conda/cli/main.py", line 69, in main_subshell
        exit_code = do_call(args, p)
      File "/home/amax/anaconda3/lib/python3.10/site-packages/conda/cli/conda_argparse.py", line 122, in do_call
        return getattr(module, func_name)(args, parser)
      File "/home/amax/anaconda3/lib/python3.10/site-packages/conda/notices/core.py", line 121, in wrapper
        return func(*args, **kwargs)
      File "/home/amax/anaconda3/lib/python3.10/site-packages/conda/cli/main_install.py", line 20, in execute
        install(args, parser, 'install')
      File "/home/amax/anaconda3/lib/python3.10/site-packages/conda/cli/install.py", line 264, in install
        unlink_link_transaction = solver.solve_for_transaction(
      File "/home/amax/anaconda3/lib/python3.10/site-packages/conda/core/solve.py", line 134, in solve_for_transaction
        unlink_precs, link_precs = self.solve_for_diff(update_modifier, deps_modifier,
      File "/home/amax/anaconda3/lib/python3.10/site-packages/conda/core/solve.py", line 177, in solve_for_diff
        final_precs = self.solve_final_state(update_modifier, deps_modifier, prune, ignore_pinned,
      File "/home/amax/anaconda3/lib/python3.10/site-packages/conda/core/solve.py", line 282, in solve_final_state
        ssc = self._collect_all_metadata(ssc)
      File "/home/amax/anaconda3/lib/python3.10/site-packages/conda/common/io.py", line 84, in decorated
        return f(*args, **kwds)
      File "/home/amax/anaconda3/lib/python3.10/site-packages/conda/core/solve.py", line 449, in _collect_all_metadata
        index, r = self._prepare(prepared_specs)
      File "/home/amax/anaconda3/lib/python3.10/site-packages/conda/core/solve.py", line 1064, in _prepare
        reduced_index = get_reduced_index(self.prefix, self.channels,
      File "/home/amax/anaconda3/lib/python3.10/site-packages/conda/core/index.py", line 267, in get_reduced_index
        new_records = SubdirData.query_all(spec, channels=channels, subdirs=subdirs,
      File "/home/amax/anaconda3/lib/python3.10/site-packages/conda/core/subdir_data.py", line 169, in query_all
        result = tuple(chain.from_iterable(executor.map(subdir_query, channel_urls)))
      File "/home/amax/anaconda3/lib/python3.10/concurrent/futures/_base.py", line 621, in result_iterator
        yield _result_or_cancel(fs.pop())
      File "/home/amax/anaconda3/lib/python3.10/concurrent/futures/_base.py", line 319, in _result_or_cancel
        return fut.result(timeout)
      File "/home/amax/anaconda3/lib/python3.10/concurrent/futures/_base.py", line 458, in result
        return self.__get_result()
      File "/home/amax/anaconda3/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
        raise self._exception
      File "/home/amax/anaconda3/lib/python3.10/concurrent/futures/thread.py", line 58, in run
        result = self.fn(*self.args, **self.kwargs)
      File "/home/amax/anaconda3/lib/python3.10/site-packages/conda/core/subdir_data.py", line 158, in subdir_query
        return tuple(
      File "/home/amax/anaconda3/lib/python3.10/site-packages/conda/core/subdir_data.py", line 174, in query
        self.load()
      File "/home/amax/anaconda3/lib/python3.10/site-packages/conda/core/subdir_data.py", line 264, in load
        _internal_state = self._load()
      File "/home/amax/anaconda3/lib/python3.10/site-packages/conda/core/subdir_data.py", line 366, in _load
        raw_repodata_str = self._repo.repodata(cache.state)  # type: ignore
      File "/home/amax/anaconda3/lib/python3.10/site-packages/conda/gateways/repodata/__init__.py", line 120, in repodata
        with conda_http_errors(self._url, filename):
      File "/home/amax/anaconda3/lib/python3.10/contextlib.py", line 153, in __exit__
        self.gen.throw(typ, value, traceback)
      File "/home/amax/anaconda3/lib/python3.10/site-packages/conda/gateways/repodata/__init__.py", line 208, in conda_http_errors
        raise RepodataIsEmpty(
      File "/home/amax/anaconda3/lib/python3.10/site-packages/conda/exceptions.py", line 462, in __init__
        body = response.json()
      File "/home/amax/anaconda3/lib/python3.10/site-packages/requests/models.py", line 975, in json
        raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
    requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

`$ /home/amax/anaconda3/bin/conda install -c fvcore -c iopath -c conda-forge fvcore iopath`

  environment variables:
                 CIO_TEST=<not set>
        CONDA_DEFAULT_ENV=sugar
                CONDA_EXE=/home/amax/anaconda3/bin/conda
             CONDA_PREFIX=/home/amax/anaconda3/envs/sugar
           CONDA_PREFIX_1=/home/amax/anaconda3
    CONDA_PROMPT_MODIFIER=(sugar)
         CONDA_PYTHON_EXE=/home/amax/anaconda3/bin/python
               CONDA_ROOT=/home/amax/anaconda3
              CONDA_SHLVL=2
           CURL_CA_BUNDLE=<not set>
          LD_LIBRARY_PATH=/home/amax/anaconda3/envs/uniad/lib:
               LD_PRELOAD=<not set>
                     PATH=/home/amax/anaconda3/envs/sugar/bin:/home/amax/anaconda3/condabin:/hom
                          e/amax/anaconda3/bin:/sbin:/bin:/usr/bin:/usr/local/bin:/snap/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>
         XRDP_SOCKET_PATH=/run/xrdp/sockdir

     active environment : sugar
    active env location : /home/amax/anaconda3/envs/sugar
            shell level : 2
       user config file : /home/czy/.condarc
 populated config files : /home/czy/.condarc
          conda version : 23.3.1
    conda-build version : 3.24.0
         python version : 3.10.9.final.0
       virtual packages : __archspec=1=x86_64
                          __cuda=12.0=0
                          __glibc=2.31=0
                          __linux=5.15.0=0
                          __unix=0=0
       base environment : /home/amax/anaconda3  (writable)
      conda av data dir : /home/amax/anaconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/fvcore/linux-64
                          https://conda.anaconda.org/fvcore/noarch
                          https://conda.anaconda.org/iopath/linux-64
                          https://conda.anaconda.org/iopath/noarch
                          http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/linux-64
                          http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/noarch
                          http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/linux-64
                          http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/noarch
                          http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/linux-64
                          http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/noarch
                          http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r/linux-64
                          http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r/noarch
          package cache : /home/amax/anaconda3/pkgs
                          /home/czy/.conda/pkgs
       envs directories : /home/amax/anaconda3/envs
                          /home/czy/.conda/envs
               platform : linux-64
             user-agent : conda/23.3.1 requests/2.31.0 CPython/3.10.9 Linux/5.15.0-78-generic ubuntu/20.04.1 glibc/2.31
                UID:GID : 1004:1004
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.

If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers? [y/N]: 
Timeout reached. No report sent.

```

I am not sure what caused this, but I successfully installed the environment on my other computer and ran the code. I have been experiencing the above error in my new computer configuration, which has been bothering me for many days.

**Comment by WeiZhang511** [comment]
Hi, I have also encountered the same issue. Have you finally found a solution regarding this problem? Thx
