### ISSUE TITLE
unable to get model working

### ISSUE THREAD

**Issue by mehdikhfifi** [Anttwo/SuGaR#144]
(sugar) khfifi@jensen:~/SuGaR$ python train.py -s /home/khfifi/tryinggauss -c /home/khfifi/gausstomesh -r "sdf"
Traceback (most recent call last):
  File "/home/khfifi/SuGaR/train.py", line 3, in <module>
    from sugar_trainers.coarse_density import coarse_training_with_density_regularization
  File "/home/khfifi/SuGaR/sugar_trainers/coarse_density.py", line 7, in <module>
    from sugar_scene.gs_model import GaussianSplattingWrapper, fetchPly
  File "/home/khfifi/SuGaR/sugar_scene/gs_model.py", line 6, in <module>
    from gaussian_splatting.scene.gaussian_model import GaussianModel
  File "/home/khfifi/SuGaR/gaussian_splatting/scene/__init__.py", line 16, in <module>
    from scene.dataset_readers import sceneLoadTypeCallbacks
  File "/home/khfifi/SuGaR/./gaussian_splatting/scene/__init__.py", line 16, in <module>
    from scene.dataset_readers import sceneLoadTypeCallbacks
  File "/home/khfifi/SuGaR/./gaussian_splatting/scene/dataset_readers.py", line 24, in <module>
    from scene.gaussian_model import BasicPointCloud
  File "/home/khfifi/SuGaR/./gaussian_splatting/scene/gaussian_model.py", line 20, in <module>
    from simple_knn._C import distCUDA2
ImportError: /home/khfifi/SuGaR/gaussian_splatting/submodules/simple-knn/simple_knn/_C.cpython-39-x86_64-linux-gnu.so: undefined symbol: _ZN3c106SymInt19promote_to_negativeEv

i'm trying to follow the steps, i'm on the optimization of sugar, and I keep running into this error. thank you to whoever replies.

**Comment by hanjoonwon** [comment]
> (sugar) khfifi@jensen:~/SuGaR$ python train.py -s /home/khfifi/tryinggauss -c /home/khfifi/gausstomesh -r "sdf" Traceback (most recent call last): File "/home/khfifi/SuGaR/train.py", line 3, in from sugar_trainers.coarse_density import coarse_training_with_density_regularization File "/home/khfifi/SuGaR/sugar_trainers/coarse_density.py", line 7, in from sugar_scene.gs_model import GaussianSplattingWrapper, fetchPly File "/home/khfifi/SuGaR/sugar_scene/gs_model.py", line 6, in from gaussian_splatting.scene.gaussian_model import GaussianModel File "/home/khfifi/SuGaR/gaussian_splatting/scene/**init**.py", line 16, in from scene.dataset_readers import sceneLoadTypeCallbacks File "/home/khfifi/SuGaR/./gaussian_splatting/scene/**init**.py", line 16, in from scene.dataset_readers import sceneLoadTypeCallbacks File "/home/khfifi/SuGaR/./gaussian_splatting/scene/dataset_readers.py", line 24, in from scene.gaussian_model import BasicPointCloud File "/home/khfifi/SuGaR/./gaussian_splatting/scene/gaussian_model.py", line 20, in from simple_knn._C import distCUDA2 ImportError: /home/khfifi/SuGaR/gaussian_splatting/submodules/simple-knn/simple_knn/_C.cpython-39-x86_64-linux-gnu.so: undefined symbol: _ZN3c106SymInt19promote_to_negativeEv
> 
> i'm trying to follow the steps, i'm on the optimization of sugar, and I keep running into this error. thank you to whoever replies.

are you clone git clone https://github.com/Anttwo/SuGaR.git --recursive ??  not  git clone https://github.com/Anttwo/SuGaR.git

**Comment by agouloumis** [comment]
I've got the same problem. I don't know what to do

**Comment by KrOverdulve** [comment]
Apparently the cause of this issue is a mismatch between PyTorch versions. What worked for me was to remove the submodule (simple_knn and diff_gaussian_rasterization) folders entirely (if you did not make changes in them of course :-), then load them again through `git submodule update --init --recursive` and reinstall the modules through

```
pip install submodules/simple-knn/
pip install submodules/diff-gaussian-rasterization/
```

There may be better ways that delve deeper into the 'why' of the problem. But this worked for me.

**Comment by Myzz2003** [comment]
I've got the same issue and solved by manually install:
```bash
pip install gaussian_splatting/submodules/simple-knn/
pip install gaussian_splatting/submodules/diff-gaussian-rasterization/
```
following @KrOverdulve 's procedure.

During the aforementioned procedure, several errors occurred and were solved by reinstall pytorch, pytorch3d, torchvision with the correct distribution according to my CUDA version. 
- I also found the auto-installed pytorch3d (by running ```python install.py```) is not compatible with the auto-installed pytorch and reinstalled them after I've done the previous installation of gs modules (simple-knn and diff-gaussian-rasterization).
- **IF you have the same issue with the auto-installed pytorch and pytorch3d, you may have to install the gs modules after the reinstallation of pytorch and pytorch3d.**
