### ISSUE TITLE
ImportError: libc10_cuda.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by Benjamin-Yan** [Anttwo/SuGaR#163]
Hi, when I run `python train_coarse_sdf.py -s ../test_data -c ../test_output` in `SuGaR` folder, I encounter the following error:
```
Traceback (most recent call last):
  File "/home/divc/user/SuGaR/train_coarse_sdf.py", line 3, in <module>
    from sugar_trainers.coarse_sdf import coarse_training_with_sdf_regularization
  File "/home/divc/user/SuGaR/sugar_trainers/coarse_sdf.py", line 5, in <module>
    from pytorch3d.loss import mesh_laplacian_smoothing, mesh_normal_consistency
  File "/home/divc/anaconda3/envs/sugar/lib/python3.9/site-packages/pytorch3d/loss/__init__.py", line 8, in <module>
    from .chamfer import chamfer_distance
  File "/home/divc/anaconda3/envs/sugar/lib/python3.9/site-packages/pytorch3d/loss/chamfer.py", line 11, in <module>
    from pytorch3d.ops.knn import knn_gather, knn_points
  File "/home/divc/anaconda3/envs/sugar/lib/python3.9/site-packages/pytorch3d/ops/__init__.py", line 7, in <module>
    from .ball_query import ball_query
  File "/home/divc/anaconda3/envs/sugar/lib/python3.9/site-packages/pytorch3d/ops/ball_query.py", line 10, in <module>
    from pytorch3d import _C
ImportError: libc10_cuda.so: cannot open shared object file: No such file or directory
```
I can't find an answer that solves my error.

**Comment by Benjamin-Yan** [comment]
When I reinstalled everything needed, this error disappeared.
