### ISSUE TITLE
AssertionError: Could not recognize scene type!

### ISSUE THREAD

**Issue by hxj2580** [Anttwo/SuGaR#188]
python gaussian_splatting/train.py -s dog_7000.ply --iterations 7000 -m out

get error:
Optimizing out
Output folder: out [27/04 17:19:20]
Tensorboard not available: not logging progress [27/04 17:19:20]
Traceback (most recent call last):
  File "/home/ubuntu/hxj/SuGaR-main/gaussian_splatting/train.py", line 219, in <module>
    training(lp.extract(args), op.extract(args), pp.extract(args), args.test_iterations, args.save_iterations, args.checkpoint_iterations, args.start_checkpoint, args.debug_from)
  File "/home/ubuntu/hxj/SuGaR-main/gaussian_splatting/train.py", line 35, in training
    scene = Scene(dataset, gaussians)
  File "/home/ubuntu/hxj/SuGaR-main/gaussian_splatting/scene/__init__.py", line 49, in __init__
    assert False, "Could not recognize scene type!"
AssertionError: Could not recognize scene type!

**Comment by interqhq** [comment]
same error ~

**Comment by NovaworksDevs** [comment]
same here, any solution?

**Comment by xiaoyaolovlife** [comment]
same here, any solution?
