### ISSUE TITLE
 [Errno 2] No such file or directory - missing point_cloud.ply 

### ISSUE THREAD

**Issue by ManuelMultiverse** [Anttwo/SuGaR#51]
Loading config C:\Users\xxxxxxxxx\SuGaR\outputs\Sculpture...
Performing train/eval split...
Found image extension .png
Traceback (most recent call last):
  File "C:\Users\xxxx\SuGaR\train.py", line 118, in <module>
    coarse_sugar_path = coarse_training_with_sdf_regularization(coarse_args)
  File "C:\Users\xxxxxxxxx\SuGaR\sugar_trainers\coarse_sdf.py", line 282, in coarse_training_with_sdf_regularization
    nerfmodel = GaussianSplattingWrapper(
  File "C:\Users\xxxxxx\SuGaR\sugar_scene\gs_model.py", line 139, in __init__
    self.gaussians.load_ply(
  File "C:\Users\xxxxxxxxx\SuGaR\gaussian_splatting\scene\gaussian_model.py", line 216, in load_ply
    plydata = PlyData.read(path)
  File "C:\Users\xxxxxxxx\anaconda3\envs\sugar\lib\site-packages\plyfile.py", line 158, in read
    (must_close, stream) = _open_stream(stream, 'read')
  File "C:\Users\xxxxxxxxx\anaconda3\envs\sugar\lib\site-packages\plyfile.py", line 1345, in _open_stream
    return (True, open(stream, read_or_write[0] + 'b'))
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\xxxx\\SuGaR\\outputs\\Sculpture\\point_cloud\\iteration_7000\\point_cloud.ply'

**Comment by yuedajiong** [comment]
run GS firstly.
like this:
python -Bu gaussian_splatting/train.py -s ../data/image/resin/output/ --iterations 7000 -m ./output/_guass_splat/

then:
python -Bu train.py -s ../data/image/resin/output/ -c ./output/_guass_splat/ -r density

modify to your real paths:  data path and checkpoint path.

**Comment by ManuelMultiverse** [comment]
Thank you, that solved the problem.
