### ISSUE TITLE
CUDA error: out of memory

### ISSUE THREAD

**Issue by zParquet** [Anttwo/SuGaR#58]
Thanks for your excellent work! I met an OOM problem when running 
```bash
python train.py -s xxx -c xxx
```
The training process is normal but the mesh cannot be extracted because of OOM problem. I am using a 24GB 3090Ti GPU and I think there is no problem of my GPU.  I tried to set image_resolution=4 in gs_model.py but it doesn't help. Could you please give some advice on this problem? Thank you!

```bash
_quaternions
torch.Size([920843, 4])
True
_sh_coordinates_dc
torch.Size([920843, 1, 3])
True
_sh_coordinates_rest
torch.Size([920843, 15, 3])
True
Number of gaussians: 920843
Opacities min/max/mean: tensor(7.0727e-05, device='cuda:0') tensor(1., device='cuda:0') tensor(0.6953, device='cuda:0')
Quantile 0.0: 7.072696462273598e-05
Quantile 0.1: 0.027714231982827187
Quantile 0.2: 0.24735727906227112
Quantile 0.3: 0.564430832862854
Quantile 0.4: 0.7604535818099976
Quantile 0.5: 0.8879363536834717
Quantile 0.6: 0.9701117277145386
Quantile 0.7: 0.9962756633758545
Quantile 0.8: 0.999401330947876
Quantile 0.9: 0.9998761415481567

Starting pruning low opacity gaussians...
WARNING! During optimization, you should use a densifier to prune low opacity points.
This function does not preserve the state of an optimizer, and sets requires_grad=False to all parameters.
Number of gaussians left: 666801
Opacities min/max/mean: tensor(0.5000, device='cuda:0') tensor(1., device='cuda:0') tensor(0.9040, device='cuda:0')
Quantile 0.0: 0.5000002980232239
Quantile 0.1: 0.6711668968200684
Quantile 0.2: 0.7912304401397705
Quantile 0.3: 0.8807359933853149
Quantile 0.4: 0.9478757977485657
Quantile 0.5: 0.9858567714691162
Quantile 0.6: 0.9970008730888367
Quantile 0.7: 0.9992061257362366
Quantile 0.8: 0.9997462630271912
Quantile 0.9: 0.9999245405197144
Processing frame 0/161...
Current point cloud for level 0.3 has 0 points.
Traceback (most recent call last):
  File "train.py", line 143, in <module>
    coarse_mesh_path = extract_mesh_from_coarse_sugar(coarse_mesh_args)[0]
  File "/data/zhangwenyuan/nerfgs/SuGaR/sugar_extractors/coarse_mesh.py", line 270, in extract_mesh_from_coarse_sugar
    frame_surface_level_outputs = sugar.compute_level_surface_points_from_camera_fast(
  File "/data/zhangwenyuan/nerfgs/SuGaR/sugar_scene/sugar_model.py", line 1778, in compute_level_surface_points_from_camera_fast
    fragments = rasterizer(mesh, cameras=p3d_cameras)
  File "/home/zhangwenyuan/anaconda3/envs/nerf/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/zhangwenyuan/anaconda3/envs/nerf/lib/python3.8/site-packages/pytorch3d/renderer/mesh/rasterizer.py", line 247, in forward
    pix_to_face, zbuf, bary_coords, dists = rasterize_meshes(
  File "/home/zhangwenyuan/anaconda3/envs/nerf/lib/python3.8/site-packages/pytorch3d/renderer/mesh/rasterize_meshes.py", line 243, in rasterize_meshes
    outputs = convert_clipped_rasterization_to_original_faces(
  File "/home/zhangwenyuan/anaconda3/envs/nerf/lib/python3.8/site-packages/pytorch3d/renderer/mesh/clip.py", line 659, in convert_clipped_rasterization_to_original_faces
    empty = torch.full(pix_to_face_clipped.shape, -1, device=device, dtype=torch.int64)
RuntimeError: CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

```

**Comment by AtlasRedux** [comment]
Easy fix, but the problem is as simple as that 24GB is not enough. I've got an RTX 4090 myself.
Just set it to use CPU for source image data. It barely affects speed and offloads almost everything into normal RAM. You lose like 5% performance on the optimizer part. With that, you can also skip lowering the resolution. I use full resolution 4K images for source, no resizing, with CPU instead.
Just add    --data_device cpu   in your optimizer CL

**Comment by cubantonystark** [comment]
@AtlasRedux would you care to specify which part of the code needs to be modified and how?

**Comment by zParquet** [comment]
I'll try it. Thank you!

**Comment by yuedajiong** [comment]
I used TitanXP, only 12G GPU RAM.  Simple scene/object(a resin toy), it is OK.

Simple object first?

**Comment by Iliceth** [comment]
@AtlasRedux Where should this `--data_device cpu` be added? As it's not an argument for train.py

**Comment by AtlasRedux** [comment]
> @AtlasRedux Where should this `--data_device cpu` be added? As it's not an argument for train.py

Yes. And yes, it is.
Here are all current available arguments:

--source_path / -s
Path to the source directory containing a COLMAP or Synthetic NeRF data set.

--model_path / -m
Path where the trained model should be stored (output/<random> by default).

--images / -i
Alternative subdirectory for COLMAP images (images by default).

--eval
Add this flag to use a MipNeRF360-style training/test split for evaluation.

--resolution / -r
Specifies resolution of the loaded images before training. If provided 1, 2, 4 or 8, uses original, 1/2, 1/4 or 1/8 resolution, respectively. For all other values, rescales the width to the given number while maintaining image aspect. If not set and input image width exceeds 1.6K pixels, inputs are automatically rescaled to this target.

--data_device
Specifies where to put the source image data, cuda by default, recommended to use cpu if training on large/high-resolution dataset, will reduce VRAM consumption, but slightly slow down training. Thanks to [HrsPythonix](https://github.com/HrsPythonix).

--white_background / -w
Add this flag to use white background instead of black (default), e.g., for evaluation of NeRF Synthetic dataset.

--sh_degree
Order of spherical harmonics to be used (no larger than 3). 3 by default.

--convert_SHs_python
Flag to make pipeline compute forward and backward of SHs with PyTorch instead of ours.

--convert_cov3D_python
Flag to make pipeline compute forward and backward of the 3D covariance with PyTorch instead of ours.

--debug
Enables debug mode if you experience erros. If the rasterizer fails, a dump file is created that you may forward to us in an issue so we can take a look.

--debug_from
Debugging is slow. You may specify an iteration (starting from 0) after which the above debugging becomes active.

--iterations
Number of total iterations to train for, 30_000 by default.

--ip
IP to start GUI server on, 127.0.0.1 by default.

--port
Port to use for GUI server, 6009 by default.

--test_iterations
Space-separated iterations at which the training script computes L1 and PSNR over test set, 7000 30000 by default.

--save_iterations
Space-separated iterations at which the training script saves the Gaussian model, 7000 30000 <iterations> by default.

--checkpoint_iterations
Space-separated iterations at which to store a checkpoint for continuing later, saved in the model directory.

--start_checkpoint
Path to a saved checkpoint to continue training from.

--quiet
Flag to omit any text written to standard out pipe.

--feature_lr
Spherical harmonics features learning rate, 0.0025 by default.

--opacity_lr
Opacity learning rate, 0.05 by default.

--scaling_lr
Scaling learning rate, 0.005 by default.

--rotation_lr
Rotation learning rate, 0.001 by default.

--position_lr_max_steps
Number of steps (from 0) where position learning rate goes from initial to final. 30_000 by default.

--position_lr_init
Initial 3D position learning rate, 0.00016 by default.

--position_lr_final
Final 3D position learning rate, 0.0000016 by default.

--position_lr_delay_mult
Position learning rate multiplier (cf. Plenoxels), 0.01 by default.

--densify_from_iter
Iteration where densification starts, 500 by default.

--densify_until_iter
Iteration where densification stops, 15_000 by default.

--densify_grad_threshold
Limit that decides if points should be densified based on 2D position gradient, 0.0002 by default.

--densification_interval
How frequently to densify, 100 (every 100 iterations) by default.

--opacity_reset_interval
How frequently to reset opacity, 3_000 by default.

--lambda_dssim
Influence of SSIM on total loss from 0 to 1, 0.2 by default.

--percent_dense
Percentage of scene extent (0--1) a point must exceed to be forcibly densified, 0.01 by default.

**Comment by AtlasRedux** [comment]
> @AtlasRedux Where should this `--data_device cpu` be added? As it's not an argument for train.py

As with all SuGaR arguments, they do the same as the original 3DGS arguments and they go into the gs_model.py.
Change self.data_device = "cuda" to self.data_device = "cpu"

**Comment by Iliceth** [comment]
> > @AtlasRedux Where should this `--data_device cpu` be added? As it's not an argument for train.py
> 
> As with all SuGaR arguments, they do the same as the original 3DGS arguments and they go into the gs_model.py. Change self.data_device = "cuda" to self.data_device = "cpu"

Thanks!

**Comment by Iliceth** [comment]
@AtlasRedux It didn't change anything for me, it seems. It starts at 7000, goes to 9000 and then SDF regularization with `tensor(xxxxx, device='cuda:0')` from 9000 to 15000. And OOM when the coarse mesh construction is started.

**Comment by Iliceth** [comment]
@AtlasRedux I found gs_model.py in the sugar_scene directory and changed cuda to cpu, but I experience the exact same behaviour, so I might be missing something? Or other things that need to be adjusted?

**Comment by diegobc11** [comment]
Same here, I have a 16GB GPU and I usually get CUDA out of memory error, changing data_device from 'cuda' to 'cpu' in gs_model.py does not solve the issue

**Comment by zParquet** [comment]
Update: I didn't find a useful solution for this, but is seeems that this problem is not stably reproducible. I didn't meet this problem later. Possibly it is affected by the python environment, linux status, unexpected code bugs, or other factors.
