### ISSUE TITLE
Point cloud normals missing error

### ISSUE THREAD

**Issue by Iliceth** [Anttwo/SuGaR#62]
Hello all, I took a 3DGS which I had already trained with the original repo's method and then used the path to it's 7000 iteration checkpoint in the command for SuGaR. All seemed to go well, it got to 15000, but then this error and the process stopped.

```
-----Foreground mesh-----
Computing points, colors and normals...
Cleaning Point Cloud...
Finished computing points, colors and normals.
Now computing mesh...
Traceback (most recent call last):
  File "/home/user/Documents/SuGaR/train.py", line 143, in <module>
    coarse_mesh_path = extract_mesh_from_coarse_sugar(coarse_mesh_args)[0]
  File "/home/user/Documents/SuGaR/sugar_extractors/coarse_mesh.py", line 387, in extract_mesh_from_coarse_sugar
    o3d_fg_mesh, o3d_fg_densities = o3d.geometry.TriangleMesh.create_from_point_cloud_poisson(
RuntimeError: [Open3D Error] (static std::tuple<std::shared_ptr<open3d::geometry::TriangleMesh>, std::vector<double, std::allocator<double> > > open3d::geometry::TriangleMesh::CreateFromPointCloudPoisson(const open3d::geometry::PointCloud&, size_t, float, float, bool, int)) /root/Open3D/cpp/open3d/geometry/SurfaceReconstructionPoisson.cpp:732: Point cloud has no normals
```
I read the error, but I'm unaware of why this is. Can someone clarify and tell me how to resolve this please? Thanks!

**Comment by Anttwo** [comment]
Hello @Iliceth,

May I ask the following questions:
1. What OS are you using?
2. What does your scene look like? Does it have some objects centered in the scene (with regard to your training camera positions)? 
 
By default, SuGaR separates the scene into a foreground volume and a background volume. Generally, the foreground is supposed to contain the most important objects you want to reconstruct, but the background is able to reconstruct detailed objects as well, as it has the same budget of vertices than the foreground. 
By default, the foreground is computed as the bounding box of the training camera positions (this definition is coherent with the vanilla Gaussian Splatting's code, and is generally a really good candidate for foreground). The user is free to provide a custom foreground bounding box to the `train.py` script. 

Currently, the code expects the foreground volume not to be empty, so it triggers an error (such as "empty normals", for example) if it does not detect any surface point inside the bounding box.
If you are trying to reconstruct a room (just like the *Playroom* and *DrJohnson* scenes from the DeepBlending dataset), the objects you're interested in reconstructing may not be located inside the bounding box of the camera positions, but outside: For instance, if you are scanning a room, then the walls, ceiling and floor are typically outside this bounding box. This is not a big deal in general, as most of the time there is a few objects located inside the foreground bounding box (such as toys in the *Playroom* scene, or chairs in the *DrJohnson* scene), so the code does not trigger an error. However, if there is no object inside your foreground box, then it might cause your error.

If this is the case, the fix is actually really simple, I just need to add an `if` block to skip the foreground mesh reconstruction if no points are detected in the foreground. I should definitely add this!

**Comment by Iliceth** [comment]
Thanks a lot for this reaction, @Anttwo, this helps understand what's going on.

To answer your questions: 

1. I run my test on Ubuntu 22.04, with miniconda for the environment.
2. The scene consists of a model standing in front of a black cloth, very simple and only 16 images.
![image](https://github.com/Anttwo/SuGaR/assets/68381834/21ad4bf7-3a3c-4783-aecd-628cb6a50dc0)

I used this scene succesfully before with the code from `gaussian-splatting`, `instant-npg` and `neuralangelo`, to name a few, but maybe here it's difficult? The requirements you describe for the foreground seem to be met, but the background is on most images like a dark void, so to speak, with very little detail. So that might be the empty volume instead?

Otherwise, it's not a 360°, is that an issue? With `neuralangelo`, it fills in the back of the model itself to create the mesh, but that might be not ideal?

To be honest, I haven't tried any other scene yet, as I always start with this one, due to it being light-weight.

**Comment by johnren-code** [comment]
Same Question. Looking forward to updated code.

**Comment by Anttwo** [comment]
Hello @Iliceth,

Alright, so after taking a look at your image, it seems the problem is indeed an empty foreground!
As you can see in the following image, there is actually no SfM point/no content inside the bounding box of the camera positions:

![camera_bbox](https://github.com/Anttwo/SuGaR/assets/65666237/508c92df-e0e7-4f5a-b7c9-b5dea5705656)

The default camera bbox is well adapted to 360 scenes (because the camera travels around the object), but not to "*face-forward*" scenes, which seems to be the type of scene you want to reconstruct.
In your case, I think that taking as the foreground bbox a box slightly larger than the bounding box of the initial SfM points (the points reconstructed with COLMAP) would be a good idea. I should definitely add this option to the code.

In the meantime, you can still run the script with no error: 
1. You first need to compute the bounding box containing your initial points by yourself (just compute the min and max of X, Y, Z coordinates of the SfM points)
2. Then provide it as an argument to the `train.py` script. Please see the `README.md` file for more details:

![bbox_args](https://github.com/Anttwo/SuGaR/assets/65666237/ab96a604-f461-4ef4-a5bb-309e05c3132f)


Looking forward to your reply!

**Comment by Iliceth** [comment]
Thanks again for the reply, @Anttwo.

To be perfectly honest, when you wrote "just compute the min and max of X, Y, Z coordinates of the SfM points", I didn't really know where to start. Probably easy and/or right under my eyes, but my noobness is too big still. I tried (-16, -16, -16) and (16, 16, 16) for min and max, after first trying half that, as I saw no numbers greater than 16 passing during the training and remembered the bounding box numbers from `instant-ngp`, which were powers of 2 too. And success. :-)

![Screenshot from 2024-01-02 13-09-37](https://github.com/Anttwo/SuGaR/assets/68381834/39446bfb-27c2-403e-a8ca-63cc450017f2)

The results are full of floaters but that's of course due to the very low image count. Left is coarse, right is fine.

![Screenshot from 2024-01-02 13-25-18](https://github.com/Anttwo/SuGaR/assets/68381834/fdc0dea9-18f8-4767-a3c6-be2ea8c7e5c5)

![Screenshot from 2024-01-02 13-25-57](https://github.com/Anttwo/SuGaR/assets/68381834/15f22f78-4d06-4275-a714-56599d5536fc)

Will try it out with other scenes, also 360* and such, but will have to keep it low with the image count, as I got an OOM in the fine mesh step. Will save up for another GPU. ;-)

So this wasn't an issue of your code, but simply due to my choices, as you expected.

An extra question, if I may: now we use colmap and then the original gaussian-splatting 0 to 7000 steps, before your code takes over, so to speak. Then it continues 7000 to 15000 and constructs the coarse mesh from that. For the fine version, as far as I can tell, it takes the original colmap point cloud again, trains from 0 to 15000 and then constructs the fine mesh. So this means something is different 3DGS-wise between the first 0 to 7000, the 7000-15000 and then the 0-15000?
