### ISSUE TITLE
Error in training with the latest changes for the real-time viewer

### ISSUE THREAD

**Issue by minar09** [Anttwo/SuGaR#83]
Hi, thank you so much for this **ultra-awesome** project. With your latest changes from today including the real-time viewer, I am getting an error in running the training script. Here's the error trace given below. Huge thanks.

````
Loading config output/custom/...

Performing train/eval split...

Traceback (most recent call last):

  File "/home/sugar/train.py", line 127, in <module>
    coarse_sugar_path = coarse_training_with_density_regularization(coarse_args)

  File "/home/sugar/sugar_trainers/coarse_density.py", line 286, in coarse_training_with_density_regularization
    nerfmodel = GaussianSplattingWrapper(

  File "/home/sugar/sugar_scene/gs_model.py", line 111, in __init__
    cam_list = load_gs_cameras(

  File "/home/sugar/sugar_scene/cameras.py", line 36, in load_gs_cameras
    extension = '.' + os.listdir(image_dir)[0].split('.')[-1]

IndexError: list index out of range
```
`

**Comment by minar09** [comment]
Sorry, I guess there was an issue with my custom data. Running now. Thanks.
