### ISSUE TITLE
my_dataset/sparse/0/points3D.ply is missing, how can I obtain it ?

### ISSUE THREAD

**Issue by clement-chupin** [Anttwo/SuGaR#91]
After classical colmap dataset creation and gaussian splatting optimization, I would like to run the SuGaR mesh creation, but my points3D.ply is missing, how can I solve this problem ?

**Comment by Anttwo** [comment]
Hello @clement-chupin,

Mmh Indeed, this looks strange; Gaussian Splatting optimization should generate a point3D.ply file if everything goes well.

Can I ask if you used the default configuration for optimizing SuGaR, or if you provided different arguments to the script?

**Comment by jiangyixing** [comment]
> 在经典的 colmap 数据集创建和高斯泼溅优化之后，我想运行 SuGaR 网格创建，但我的 point3D.ply 丢失了，我该如何解决这个问题？

me too

**Comment by nbmontasufv** [comment]
Hi, thank for sharing your work with everybody:

I have the same issue over here: 
=>  No .ply, no ./output/refined_ply/<your scene name>/ directory created either.

Error message:
RPly: Unable to open file
[Open3D WARNING] Read PLY failed: unable to open file: ./output/coarse_mesh\gaussian_splatting\data\templos\01\sugarmesh_coarse\gaussian_splatting\data\templos\01\3Dgs7000_sdfestim02_sdfnorm02_level03_decim1000000.ply
Mesh to bind to loaded.
Binding radiance cloud to surface mesh...
Traceback (most recent call last):
  File "D:\sugar_local_clone\SuGaR\train.py", line 170, in <module>
    refined_sugar_path = refined_training(refined_args)
  File "D:\sugar_local_clone\SuGaR\sugar_trainers\refine.py", line 396, in refined_training
    sugar = SuGaR(
  File "D:\sugar_local_clone\SuGaR\sugar_scene\sugar_model.py", line 323, in __init__
    scales = scales.clamp_min(0.0000001).reshape(len(faces_verts), -1, 1).expand(-1, self.n_gaussians_per_surface_triangle, 2).clone().reshape(-1, 2)
RuntimeError: cannot reshape tensor of 0 elements into shape [0, -1, 1] because the unspecified dimension size -1 can be any value and is ambiguous

Thank you for any heads up concerning this issue.

Best, 

Nelson

**Comment by clement-chupin** [comment]
> Hi, thanks for sharing your work with everybody:
> 
> I have the same issue over here (on Windows machine): => No .ply, no ./output/refined_ply// directory created either.
> 
> Error message: RPly: Unable to open file [Open3D WARNING] Read PLY failed: unable to open file: ./output/coarse_mesh\gaussian_splatting\data\templos\01\sugarmesh_coarse\gaussian_splatting\data\templos\01\3Dgs7000_sdfestim02_sdfnorm02_level03_decim1000000.ply Mesh to bind to loaded. Binding radiance cloud to surface mesh... Traceback (most recent call last): File "D:\sugar_local_clone\SuGaR\train.py", line 170, in refined_sugar_path = refined_training(refined_args) File "D:\sugar_local_clone\SuGaR\sugar_trainers\refine.py", line 396, in refined_training sugar = SuGaR( File "D:\sugar_local_clone\SuGaR\sugar_scene\sugar_model.py", line 323, in **init** scales = scales.clamp_min(0.0000001).reshape(len(faces_verts), -1, 1).expand(-1, self.n_gaussians_per_surface_triangle, 2).clone().reshape(-1, 2) RuntimeError: cannot reshape tensor of 0 elements into shape [0, -1, 1] because the unspecified dimension size -1 can be any value and is ambiguous
> 
> Thank you for any heads up concerning this issue.
> 
> Best,
> 
> Nelson

Just run gaussian_splattiing/trainpy works for me, it seems that th points3D.ply is generated by the classical GS process.
